lib/ex_money_web/router.ex
defmodule ExMoney.Web.Router do
  use ExMoney.Web, :router

  pipeline :browser_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :browser do
    plug :accepts, ["html", "json"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :saltedge_api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug Guardian.Plug.VerifyHeader
    plug Guardian.Plug.LoadResource
  end

  pipeline :api_auth do
    plug :accepts, ["json"]
    plug Guardian.Plug.VerifyHeader, realm: "Token"
    plug Guardian.Plug.LoadResource
  end

  scope "/", ExMoney.Web do
    pipe_through [:browser, :browser_session]

    get "/", DashboardController, :overview

    get "/login", SessionController, :new, as: :login
    get "/setup/new", SetupController, :new
    post "/setup/complete", SetupController, :complete
    post "/login", SessionController, :create, as: :login
    delete "/logout", SessionController, :delete, as: :logout
    get "/logout", SessionController, :delete, as: :logout

    scope "/dashboard" do
      get "/", DashboardController, :overview
      get "/overview", DashboardController, :overview
    end

    scope "/settings", Settings, as: :settings do
      get "/user", UserController, :edit
      put "/user", UserController, :update
      resources "/accounts", AccountController
      get "/categories/sync", CategoryController, :sync
      resources "/categories", CategoryController
      resources "/rules", RuleController
      resources "/logins", LoginController, only: [:index, :delete, :show]
    end

    resources "/transactions", TransactionController
  end

  scope "/m", ExMoney.Web.Mobile, as: :mobile do
    pipe_through [:browser, :browser_session]

    get "/", StartController, :index
    get "/dashboard", DashboardController, :overview
    get "/overview", DashboardController, :overview
    get "/login", SessionController, :new, as: :login
    post "/login", SessionController, :create, as: :login
    get "/accounts/:id/refresh", AccountController, :refresh
    get "/accounts/:id/expenses", AccountController, :expenses
    get "/accounts/:id/income", AccountController, :income
    resources "/accounts", AccountController, only: [:show]
    resources "/transactions", TransactionController
    post "/transactions/create_from_fav", TransactionController, :create_from_fav

    resources "/favourite_transactions", FavouriteTransactionController do
      put "/fav", FavouriteTransactionController, :fav, as: :fav, param: "id"
    end

    get "/logged_in", LoggedInController, :index
    get "/budget", BudgetController, :index
    get "/budget/expenses", BudgetController, :expenses
    get "/budget/income", BudgetController, :income
    resources "/budget_history", BudgetHistoryController, only: [:index, :show]

    scope "/settings", as: :setting do
      get "/", SettingController, :index
      resources "/budget", Setting.BudgetController, only: [:new, :show, :edit, :update, :create], singleton: true do
        post "/apply", Setting.BudgetController, :apply
      end
      resources "/budget_items", Setting.BudgetItemController, only: [:delete]

      resources "/categories", Setting.CategoryController, only: [:index, :edit, :update]
    end
  end

  scope "/saltedge", ExMoney.Web.Saltedge, as: :saltedge do
    pipe_through [:browser, :browser_session]

    scope "/logins" do
      get "/new", LoginController, :new
      get "/:id/sync", LoginController, :sync
    end

    scope "/accounts" do
      get "/sync", AccountController, :sync
    end
  end

  scope "/callbacks", ExMoney.Web.Callbacks, as: :callbacks do
    pipe_through [:saltedge_api, :browser_session]

    post "/success", SuccessCallbackController, :success, as: :success
    post "/failure", FailureCallbackController, :failure, as: :failure
    post "/notify", NotifyCallbackController, :notify, as: :notify
    post "/interactive", InteractiveCallbackController, :interactive, as: :interactive
    post "/destroy", DestroyCallbackController, :destroy, as: :destroy
  end

  scope "/api/v2", ExMoney.Web.Api.V2, as: :api do
    pipe_through [:api_auth]

    post "/login", SessionController, :login
    resources "/accounts", AccountController, only: [:index]
    resources "/categories", CategoryController, only: [:index]
    get "/transactions/recent", TransactionController, :recent, as: :recent
    get "/sync", SyncController, :index
  end

  scope "/api/v1", ExMoney.Web.Api.V1, as: :api do
    pipe_through [:api]

    get "/session/relogin", SessionController, :relogin
  end
end

lib/ex_money_web/views/layout_view.ex
defmodule ExMoney.Web.LayoutView do
  use ExMoney.Web, :view
end

lib/ex_money_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ExMoney</title>

    <link href="<%= static_path(@conn, "/css/bootstrap.css") %>" rel="stylesheet">
    <link href="<%= static_path(@conn, "/css/app.css") %>" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">ExMoney - <%= String.capitalize(@topbar) %></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link "Dashboard", to: dashboard_path(@conn, :overview) %></li>
            <li><%= link "Settings", to: settings_login_path(@conn, :index) %></li>
            <li><a href="https://github.com/gaynetdinov/ex_money">Help</a></li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <%= render @view_module, @view_template, assigns %>
    </div>

    <script src="<%= static_path(@conn, "/js/vendor.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/ex_money_web/templates/layout/login.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>ExMoney Signin</title>

    <link href="<%= static_path(@conn, "/css/vendor.css") %>" rel="stylesheet">
    <link href="<%= static_path(@conn, "/css/app.css") %>" rel="stylesheet">
  </head>

  <body>
    <div class="container">
      <%= render @view_module, @view_template, assigns %>
    </div>
  </body>
</html>

lib/ex_money_web/templates/layout/mobile.html.eex
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no, viewport-fit=cover">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="theme-color" content="#2196f3">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="format-detection" content="telephone=no">
    <meta name="csrf" content="<%= Plug.CSRFProtection.get_csrf_token %>">
    <%= if Guardian.Plug.current_token(@conn) do %>
      <meta name='guardian_token' content="<%= Guardian.Plug.current_token(@conn) %>">
    <% end %>
    <link rel="apple-touch-icon" sizes="120x120" href="/images/apple-touch-icon.png">
    <title>ExMoney</title>

    <link href="<%= static_path(@conn, "/css/app.css") %>" rel="stylesheet">
    <link href="<%= static_path(@conn, "/css/framework7.css") %>" rel="stylesheet">
    <link href="<%= static_path(@conn, "/css/framework7-keypad.css") %>" rel="stylesheet">
  </head>

  <body>
    <div id="app">
      <div class="statusbar"></div>

      <div class="panel panel-left panel-reveal" style="background: #bfbfc5;">
        <div class="card">
          <div class="card-header"><strong>ExMoney</strong></div>
          <div class="card-content">
            <div class="list">
              <ul>
                <a href="/m/dashboard" class="link item-link item-content panel-close no-animation">
                  <div class="item-inner">
                    <div class="item-title">Dashboard</div>
                  </div>
                </a>
                <a href="/m/budget" class="link item-link item-content panel-close" data-animate="false" data-ignore-cache="true">
                  <div class="item-inner">
                    <div class="item-title">Budget</div>
                  </div>
                </a>
                <a href="/m/budget_history" class="link item-link item-content panel-close no-animation" data-ignore-cache="true">
                  <div class="item-inner">
                    <div class="item-title">Budget History</div>
                  </div>
                </a>
                <a href="/m/settings" class="link item-link item-content panel-close no-animation" data-ignore-cache="true">
                  <div class="item-inner">
                    <div class="item-title">Settings</div>
                  </div>
                </a>
              </ul>
            </div>
          </div>
        </div>
      </div>

      <%= render @view_module, @view_template, assigns %>
    </div>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/ex_money_web/templates/layout/setup.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ExMoney First Run</title>

    <link href="<%= static_path(@conn, "/css/vendor.css") %>" rel="stylesheet">
    <link href="<%= static_path(@conn, "/css/app.css") %>" rel="stylesheet">
  </head>
  <body>
    <div class="container-fluid">
      <%= render @view_module, @view_template, assigns %>
    </div>

    <script src="<%= static_path(@conn, "/js/vendor.js") %>"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>