lib/ex_money_web/router.ex
defmodule ExMoney.Web.Router do
  use ExMoney.Web, :router

  pipeline :browser_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :browser do
    plug :accepts, ["html", "json"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :saltedge_api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug Guardian.Plug.VerifyHeader
    plug Guardian.Plug.LoadResource
  end

  pipeline :api_auth do
    plug :accepts, ["json"]
    plug Guardian.Plug.VerifyHeader, realm: "Token"
    plug Guardian.Plug.LoadResource
  end

  scope "/", ExMoney.Web do
    pipe_through [:browser, :browser_session]

    get "/", DashboardController, :overview

    get "/login", SessionController, :new, as: :login
    get "/setup/new", SetupController, :new
    post "/setup/complete", SetupController, :complete
    post "/login", SessionController, :create, as: :login
    delete "/logout", SessionController, :delete, as: :logout
    get "/logout", SessionController, :delete, as: :logout

    scope "/dashboard" do
      get "/", DashboardController, :overview
      get "/overview", DashboardController, :overview
    end

    scope "/settings", Settings, as: :settings do
      get "/user", UserController, :edit
      put "/user", UserController, :update
      resources "/accounts", AccountController
      get "/categories/sync", CategoryController, :sync
      resources "/categories", CategoryController
      resources "/rules", RuleController
      resources "/logins", LoginController, only: [:index, :delete, :show]
    end

    resources "/transactions", TransactionController
  end

  scope "/m", ExMoney.Web.Mobile, as: :mobile do
    pipe_through [:browser, :browser_session]

    get "/", StartController, :index
    get "/dashboard", DashboardController, :overview
    get "/overview", DashboardController, :overview
    get "/login", SessionController, :new, as: :login
    post "/login", SessionController, :create, as: :login
    get "/accounts/:id/refresh", AccountController, :refresh
    get "/accounts/:id/expenses", AccountController, :expenses
    get "/accounts/:id/income", AccountController, :income
    resources "/accounts", AccountController, only: [:show]
    resources "/transactions", TransactionController
    post "/transactions/create_from_fav", TransactionController, :create_from_fav

    resources "/favourite_transactions", FavouriteTransactionController do
      put "/fav", FavouriteTransactionController, :fav, as: :fav, param: "id"
    end

    get "/logged_in", LoggedInController, :index
    get "/budget", BudgetController, :index
    get "/budget/expenses", BudgetController, :expenses
    get "/budget/income", BudgetController, :income
    resources "/budget_history", BudgetHistoryController, only: [:index, :show]

    scope "/settings", as: :setting do
      get "/", SettingController, :index
      resources "/budget", Setting.BudgetController, only: [:new, :show, :edit, :update, :create], singleton: true do
        post "/apply", Setting.BudgetController, :apply
      end
      resources "/budget_items", Setting.BudgetItemController, only: [:delete]

      resources "/categories", Setting.CategoryController, only: [:index, :edit, :update]
    end
  end

  scope "/saltedge", ExMoney.Web.Saltedge, as: :saltedge do
    pipe_through [:browser, :browser_session]

    scope "/logins" do
      get "/new", LoginController, :new
      get "/:id/sync", LoginController, :sync
    end

    scope "/accounts" do
      get "/sync", AccountController, :sync
    end
  end

  scope "/callbacks", ExMoney.Web.Callbacks, as: :callbacks do
    pipe_through [:saltedge_api, :browser_session]

    post "/success", SuccessCallbackController, :success, as: :success
    post "/failure", FailureCallbackController, :failure, as: :failure
    post "/notify", NotifyCallbackController, :notify, as: :notify
    post "/interactive", InteractiveCallbackController, :interactive, as: :interactive
    post "/destroy", DestroyCallbackController, :destroy, as: :destroy
  end

  scope "/api/v2", ExMoney.Web.Api.V2, as: :api do
    pipe_through [:api_auth]

    post "/login", SessionController, :login
    resources "/accounts", AccountController, only: [:index]
    resources "/categories", CategoryController, only: [:index]
    get "/transactions/recent", TransactionController, :recent, as: :recent
    get "/sync", SyncController, :index
  end

  scope "/api/v1", ExMoney.Web.Api.V1, as: :api do
    pipe_through [:api]

    get "/session/relogin", SessionController, :relogin
  end
end

lib/ex_money_web/controllers/api/v2/transaction_controller.ex
defmodule ExMoney.Web.Api.V2.TransactionController do
  use ExMoney.Web, :controller

  alias ExMoney.Transactions

  plug Guardian.Plug.EnsureAuthenticated, handler: ExMoney.Guardian.ApiUnauthenticated

  def recent(conn, _params) do
    user = Guardian.Plug.current_resource(conn)

    transactions = Transactions.recent(user.id)

    render conn, :recent, transactions: transactions
  end
end

lib/ex_money_web/controllers/mobile/account_controller.ex
defmodule ExMoney.Web.Mobile.AccountController do
  use ExMoney.Web, :controller

  alias ExMoney.DateHelper
  alias ExMoney.{Repo, Transactions, Account}

  plug Guardian.Plug.EnsureAuthenticated, handler: ExMoney.Guardian.Mobile.Unauthenticated
  plug :put_layout, "mobile.html"

  def show(conn, %{"id" => account_id} = params) do
    parsed_date = DateHelper.parse_date(params["date"])
    from = DateHelper.first_day_of_month(parsed_date)
    to = DateHelper.last_day_of_month(parsed_date)

    account = Account.by_id_with_login(account_id) |> Repo.one

    month_transactions = Transactions.by_month(account_id, from, to) |> Repo.all()

    categories = Transactions.group_by_month_by_category(account_id, from, to)
    |> Enum.reduce(%{}, fn({category, amount}, acc) ->
      {float_amount, _} = Decimal.to_string(amount, :normal)
      |> Float.parse

      positive_float = float_amount * -1

      Map.put(acc, category.id,
        %{
          id: category.id,
          humanized_name: category.humanized_name,
          css_color: category.css_color,
          amount: positive_float,
          parent_id: category.parent_id
        })
    end)

    current_month = DateHelper.current_month(parsed_date)
    previous_month = DateHelper.previous_month(parsed_date)
    next_month = DateHelper.next_month(parsed_date)

    render conn, :show,
      account: account,
      month_transactions: month_transactions,
      categories: categories,
      current_month: current_month,
      previous_month: previous_month,
      next_month: next_month
  end

  def refresh(conn, %{"id" => account_id}) do
    account = Repo.get(Account, account_id)

    render conn, :refresh, account: account
  end

  def expenses(conn, %{"date" => date, "id" => account_id}) do
    account = Repo.get!(Account, account_id)
    parsed_date = DateHelper.parse_date(date)
    from = DateHelper.first_day_of_month(parsed_date)
    to = DateHelper.last_day_of_month(parsed_date)
    account_balance = account_balance(from, to, account.id)

    transactions = Transactions.expenses_by_month(account_id, from, to)
    expenses = process_transactions(transactions)

    {:ok, formatted_date} = Timex.format(parsed_date, "%b %Y", :strftime)

    from = URI.encode_www_form("/m/accounts/#{account_id}/expenses?date=#{date}")

    render conn, :expenses,
      expenses: expenses,
      date: %{label: formatted_date, value: date},
      from: from,
      account: account,
      account_balance: account_balance
  end

  def income(conn, %{"date" => date, "id" => account_id}) do
    account = Repo.get!(Account, account_id)
    parsed_date = DateHelper.parse_date(date)
    from = DateHelper.first_day_of_month(parsed_date)
    to = DateHelper.last_day_of_month(parsed_date)
    account_balance = account_balance(from, to, account.id)

    transactions = Transactions.income_by_month(account_id, from, to)
    income = process_transactions(transactions)

    {:ok, formatted_date} = Timex.format(parsed_date, "%b %Y", :strftime)

    from = URI.encode_www_form("/m/accounts/#{account_id}/income?date=#{date}")

    render conn, :income,
      income: income,
      date: %{label: formatted_date, value: date},
      from: from,
      account: account,
      account_balance: account_balance
  end

  defp account_balance(from, to, account_id) do
    ExMoney.Accounts.get_account_history_balance(from, to)
    |> Enum.reduce(%{}, fn(history, acc) ->
      inserted_at =
        history.inserted_at
        |> NaiveDateTime.to_date()
        |> Date.to_string()

      Map.put(acc, inserted_at, history.state[to_string(account_id)])
    end)
  end

  defp process_transactions(transactions) do
    transactions
    |> Enum.group_by(fn(transaction) -> transaction.made_on end)
    |> Enum.sort(fn({date_1, _transactions}, {date_2, _transaction}) ->
      Date.compare(date_1, date_2) != :lt
    end)
  end
end

lib/ex_money_web/controllers/mobile/budget_controller.ex
defmodule ExMoney.Web.Mobile.BudgetController do
  use ExMoney.Web, :controller

  alias ExMoney.DateHelper
  alias ExMoney.{Repo, Transactions, Budget}

  plug Guardian.Plug.EnsureAuthenticated, handler: ExMoney.Guardian.Mobile.Unauthenticated
  plug :put_layout, "mobile.html"

  def index(conn, params) do
    user = Guardian.Plug.current_resource(conn)
    current_budget = Budget.current_by_user_id(user.id) |> Repo.one

    if current_budget do
      _index(conn, params, current_budget)
    else
      render conn, :setup
    end
  end

  defp _index(conn, params, current_budget) do
    parsed_date = DateHelper.parse_date(params["date"])
    from = DateHelper.first_day_of_month(parsed_date)
    to = DateHelper.last_day_of_month(parsed_date)

    account_ids = current_budget.accounts
    month_transactions = Transactions.by_month(account_ids, from, to) |> Repo.all()
    categories = Transactions.group_by_month_by_category_without_withdraw(account_ids, from, to)

    current_month = DateHelper.current_month(parsed_date)
    previous_month = DateHelper.previous_month(parsed_date)
    next_month = DateHelper.next_month(parsed_date)

    currency_label = if month_transactions != [] do
      List.first(month_transactions).account.currency_label
    else
      ""
    end

    categories_limits = Enum.reduce current_budget.items, %{}, fn({item_id, limit}, acc) ->
      {item_id, _} = Integer.parse(item_id)
      {limit, _} = Integer.parse(limit)
      Map.put(acc, item_id, limit)
    end

    render conn, :index,
      month_transactions: month_transactions,
      categories_limits: categories_limits,
      currency_label: currency_label,
      categories: categories,
      current_month: current_month,
      previous_month: previous_month,
      next_month: next_month
  end

  def expenses(conn, %{"date" => date}) do
    user = Guardian.Plug.current_resource(conn)
    current_budget = Budget.current_by_user_id(user.id) |> Repo.one
    parsed_date = DateHelper.parse_date(date)
    from = DateHelper.first_day_of_month(parsed_date)
    to = DateHelper.last_day_of_month(parsed_date)

    transactions = Transactions.expenses_by_month(current_budget.accounts, from, to)
    expenses = process_transactions(transactions)

    {:ok, formatted_date} = Timex.format(parsed_date, "%b %Y", :strftime)

    from = URI.encode_www_form("/m/budget/expenses?date=#{date}")

    render conn, :expenses,
      expenses: expenses,
      date: %{label: formatted_date, value: date},
      from: from
  end

  def income(conn, %{"date" => date}) do
    user = Guardian.Plug.current_resource(conn)
    current_budget = Budget.current_by_user_id(user.id) |> Repo.one
    parsed_date = DateHelper.parse_date(date)
    from = DateHelper.first_day_of_month(parsed_date)
    to = DateHelper.last_day_of_month(parsed_date)

    transactions = Transactions.income_by_month(current_budget.accounts, from, to)
    income = process_transactions(transactions)

    {:ok, formatted_date} = Timex.format(parsed_date, "%b %Y", :strftime)

    from = URI.encode_www_form("/m/budget/income?date=#{date}")

    render conn, :income,
      income: income,
      date: %{label: formatted_date, value: date},
      from: from
  end

  defp process_transactions(transactions) do
    transactions
    |> Enum.group_by(fn(transaction) -> transaction.made_on end)
    |> Enum.sort(fn({date_1, _transactions}, {date_2, _transaction}) ->
      Date.compare(date_1, date_2) != :lt
    end)
  end
end

lib/ex_money_web/controllers/mobile/budget_history_controller.ex
defmodule ExMoney.Web.Mobile.BudgetHistoryController do
  use ExMoney.Web, :controller

  plug Guardian.Plug.EnsureAuthenticated, handler: ExMoney.Guardian.Mobile.Unauthenticated
  plug :put_layout, "mobile.html"

  alias ExMoney.{Repo, Budget, Account, Category}

  def index(conn, _params) do
    user = Guardian.Plug.current_resource(conn)
    current_budget = Budget.current_by_user_id(user.id) |> Repo.one
    budgets = Budget.by_user_id(user.id) |> Repo.all()

    budgets = if current_budget do
      Enum.reject(budgets, fn(budget) -> budget.id == current_budget.id end)
    else
      budgets
    end

    render conn, :index,
      current_budget: current_budget,
      budgets: budgets
  end

  def show(conn, %{"id" => id}) do
    budget = Repo.get!(Budget, id)
    accounts =
      Enum.map(budget.accounts, fn(account_id) ->
        Repo.get(Account, account_id).name
      end) |> Enum.join(",")

    items =
      budget.items
      |> Enum.map(fn({id, v}) ->
        name = Repo.get(Category, id).humanized_name
        {amount, _} = Integer.parse(v)
        {name, amount}
      end)
      |> Enum.sort(fn({_name_1, amount_1}, {_name_2, amount_2}) -> amount_1 > amount_2 end)

    budget_expenses =
      items
      |> Enum.map(fn({_, amount}) -> amount end)
      |> Enum.sum

    render conn, :show,
      budget_expenses: budget_expenses,
      budget: budget,
      items: items,
      accounts: accounts
  end
end

lib/ex_money_web/controllers/mobile/dashboard_controller.ex
defmodule ExMoney.Web.Mobile.DashboardController do
  use ExMoney.Web, :controller

  alias ExMoney.{Repo, Transactions, Account, FavouriteTransaction}

  plug Guardian.Plug.EnsureAuthenticated, handler: ExMoney.Guardian.Mobile.Unauthenticated
  plug :put_layout, "mobile.html"

  def overview(conn, _params) do
    user = Guardian.Plug.current_resource(conn)
    last_login_at = fetch_last_login_at()
    transactions = Transactions.recent(user.id)

    new_recent_transactions = Enum.filter(transactions, fn(tr) ->
      NaiveDateTime.compare(tr.inserted_at, last_login_at) != :lt
    end)

    new_transaction_ids = Enum.map(new_recent_transactions, fn(tr) -> tr.id end)

    recent_transactions = Enum.group_by(transactions, fn(transaction) ->
      transaction.made_on
    end)
    |> Enum.sort(fn({date_1, _transactions_1}, {date_2, _transactions_2}) ->
      Date.compare(date_1, date_2) != :lt
    end)

    accounts = Account.show_on_dashboard
    |> Repo.all
    |> Enum.reduce([], fn(account, acc) ->
      new_transactions = Transactions.new_since(last_login_at, account.id)

      recent_diff = Enum.reduce(new_transactions, Decimal.new(0), fn(transaction, acc) ->
        Decimal.add(acc, transaction.amount)
      end)

      [Map.put(account, :recent_diff, recent_diff) | acc]
    end)

    render conn, :overview,
      recent_transactions: recent_transactions,
      accounts: accounts,
      new_transaction_ids: new_transaction_ids,
      fav_transaction: fav_transaction(user.id),
      changeset: Transactions.changeset_custom()
  end

  defp fav_transaction(user_id) do
    FavouriteTransaction.fav_by_user_id(user_id)
    |> Repo.one
  end

  defp fetch_last_login_at do
    case :ets.lookup(:ex_money_cache, "last_login_at") do
      [] ->
        NaiveDateTime.from_erl!(:calendar.universal_time)
      [{_key, nil}] ->
        NaiveDateTime.from_erl!(:calendar.universal_time)
      [{_key, value}] ->
        value
    end
  end
end

lib/ex_money_web/controllers/mobile/logged_in_controller.ex
defmodule ExMoney.Web.Mobile.LoggedInController do
  use ExMoney.Web, :controller

  plug Guardian.Plug.EnsureAuthenticated

  def index(conn, _params) do
    send_resp(conn, 200, "")
  end
end

lib/ex_money_web/controllers/mobile/setting/budget_item_controller.ex
defmodule ExMoney.Web.Mobile.Setting.BudgetItemController do
  use ExMoney.Web, :controller

  alias ExMoney.{Repo, BudgetItem}

  plug Guardian.Plug.EnsureAuthenticated, handler: ExMoney.Guardian.Mobile.Unauthenticated
  plug :put_layout, "mobile.html"

  def delete(conn, %{"id" => id}) do
    budget_item = Repo.get!(BudgetItem, id)

    Repo.delete!(budget_item)

    put_resp_content_type(conn, "application/json")
    |> send_resp(200, Poison.encode!(%{}))
  end
end

lib/ex_money_web/controllers/mobile/setting_controller.ex
defmodule ExMoney.Web.Mobile.SettingController do
  use ExMoney.Web, :controller

  plug Guardian.Plug.EnsureAuthenticated, handler: ExMoney.Guardian.Mobile.Unauthenticated
  plug :put_layout, "mobile.html"

  def index(conn, _params) do
    render conn, :index
  end
end

lib/ex_money_web/controllers/mobile/start_controller.ex
defmodule ExMoney.Web.Mobile.StartController do
  use ExMoney.Web, :controller

  plug :put_layout, "mobile.html"

  def index(conn, _params) do
    render conn, :index
  end
end

lib/ex_money_web/views/mobile/budget_history_view.ex
defmodule ExMoney.Web.Mobile.BudgetHistoryView do
  use ExMoney.Web, :view
end

lib/ex_money_web/templates/mobile/transaction/categories_list.html.eex
<select class="form-control" id="transaction_category_id" name="transaction[category_id]">
  <%= for {{name, id}, sub_categories} <- @categories do %>
    <option <%= if id == @selected, do: "selected=selected" %> value="<%= id %>">
      <%= name %>
    </option>

    <%= for {name, id} <- sub_categories do %>
      <option <%= if id == @selected, do: "selected=selected" %> value="<%= id %>">
        &#8627;&nbsp;<%= name %>
      </option>
    <% end %>
  <% end %>
</select>

lib/ex_money_web/templates/mobile/transaction/edit.html.eex
<div class="view view-main">
  <div class="page navbar-fixed" data-name="edit-transaction-screen">
    <div class="navbar">
      <div class="navbar-inner">
        <div class="left">
          <a href="#" class="link back back-to-dashboard">
            <i class="icon icon-back"></i>&nbsp; Back
          </a>
        </div>
        <div class="center">Edit transaction</div>
        <div class='right'></div>
      </div>
    </div>
    <div class="page-content">
      <div class="list reduced-margin">
        <%= form_for @changeset, mobile_transaction_path(@conn, :update, @transaction), [method: :put, class: "form-ajax-submit"], fn f -> %>
          <%= hidden_input(f, :from, value: @from) %>
          <ul>
            <li>
              <a href="#" class="item-link smart-select smart-select-init" data-close-on-select="true" data-open-in="popup" data-searchbar="true" data-page-title="Choose Category">
                <%= render "categories_list.html", categories: @categories, selected: @transaction.category_id %>
                <div class="item-content">
                  <div class="item-inner">
                    <div class="item-title">Category</div>
                  </div>
                </div>
              </a>
            </li>
            <li class="align-top">
              <div class="item-content">
                <div class="item-inner">
                  <div class="item-title label">Note</div>
                  <div class="item-input">
                    <%= textarea(f, :description, placeholder: "Note") %>
                  </div>
                </div>
              </div>
            </li>
          </ul>

          <div class="block">
            <div class="row">
              <div class="col-100" align="center">
                <button class="button active button-fill button-big" type="submit">Update</button>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

lib/ex_money_web/templates/mobile/transaction/index.html.eex
<div class="view view-main">
  <div class="page navbar-fixed" data-name="transactions-screen">
    <div class="navbar">
      <div class="navbar-inner">
        <div class="left">
          <a href="/m/<%= @slug %>?date=<%= @date.value %>" class="link back" data-force="true" data-ignore-cache="true">
            <i class="icon icon-back"></i>&nbsp; Back
          </a>
        </div>
        <div class="center"><%= @category %></div>
        <div class="right"></div>
      </div>
    </div>
    <div class="page-content hide-navbar-on-scroll">
      <div class="list reduced-margin media-list">
        <%= if length(@transactions) == 0 do %>
          <div class="content-block">
            There are no transactions for such category anymore.
          </div>
        <% else %>
          <%= render ExMoney.Web.SharedView, "transactions_list.html",
            transactions: @transactions,
            new_transaction_ids: [],
            account: nil,
            account_balance: nil,
            from: @from %>
          <% end %>
      </div>
    </div>
  </div>
</div>

lib/ex_money_web/templates/mobile/transaction/new.html.eex
<div class="view view-main">
  <div class="page navbar-fixed" data-name="new-transaction-screen">
    <div class="navbar">
      <div class="navbar-inner">
        <div class="left">
          <a href="/m/dashboard" class="link back" id="new_transaction_back">
            <i class="icon icon-back"></i>&nbsp; Back
          </a>
        </div>
        <div class="center">New transaction</div>
        <div class='right'></div>
      </div>
    </div>
    <div class="page-content">
      <div class="list reduced-margin">
        <%= form_for @changeset, mobile_transaction_path(@conn, :create), [method: :post, class: "form-ajax-submit"], fn f -> %>
          <ul>
            <li>
              <div class="item-content">
                <div class="item-inner">
                  <div class="item-title label">Amount</div>
                  <div class="item-input">
                    <%= text_input(f, :amount, placeholder: "0.00", id: "new-transaction-amount", style: "text-align: right") %>
                  </div>
                </div>
              </div>
            </li>
            <li>
              <div class="item-content">
                <div class="item-inner">
                  <p class="segmented segmented-raised" style='width:100%'>
                    <a href='#' id='expense-button' class="button button-active">Expense</a>
                    <a href='#' id='income-button' class="button button">Income</a>
                  </p>
                  <div class="item-input">
                    <%= hidden_input(f, :type, value: "expense") %>
                  </div>
                </div>
              </div>
            </li>
            <li>
              <a href="#" class="item-link smart-select smart-select-init" data-close-on-select="true" data-open-in="popup">
                <%= select(f, :account_id, @accounts) %>
                <div class="item-content">
                  <div class="item-inner">
                    <div class="item-title">Account</div>
                  </div>
                </div>
              </a>
            </li>
            <li>
              <a href="#" class="item-link smart-select smart-category-init" data-close-on-select="true" data-open-in="popup" data-searchbar="true" data-page-title="Choose Category">
                <%= render "categories_list.html", categories: @categories, selected: nil %>
                <div class="item-content">
                  <div class="item-inner">
                    <div class="item-title">Category</div>
                  </div>
                </div>
              </a>
            </li>
            <li>
              <div class="item-content">
                <div class="item-inner">
                  <div class="item-title label">Made on</div>
                  <div class="item-input">
                    <%= text_input(f, :made_on, placeholder: "Date", style: "text-align: right") %>
                  </div>
                </div>
              </div>
            </li>
            <li>
              <div class="item-content">
                <div class="item-inner">
                  <div class="item-title label">Note</div>
                  <div class="item-input">
                    <%= text_input(f, :description, placeholder: "Note", style: "text-align: right") %>
                  </div>
                </div>
              </div>
            </li>
          </ul>

          <div class="block">
            <div class="row">
              <div class="col-100" align="center">
                <button class="button active button-big button-fill" type="submit">Add</button>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

lib/ex_money_web/templates/mobile/transaction/show.html.eex
<div class="view view-main">
  <div class="page navbar-fixed" data-name="show-transaction-screen">
    <div class="navbar">
      <div class="navbar-inner">
        <div class="left">
          <a href="#" class="link back back-to-dashboard">
            <i class="icon icon-back"></i>&nbsp; Back
          </a>
        </div>
        <div class="center">Transaction</div>
        <div class='right'></div>
      </div>
    </div>
    <div class="page-content">
      <div class="data-table card">
        <table>
          <tbody>
            <tr>
              <td colspan="2"><strong>Transaction</strong></td>
            </tr>
            <tr>
              <td class="label-cell">Id</td>
              <td><%= @transaction.saltedge_transaction_id %></td>
            </tr>
            <tr>
              <td class="label-cell">Description</td>
              <td><%= @transaction.description %></td>
            </tr>
            <tr class="label-cell">
              <td>Currency</td>
              <td><%= @transaction.currency_code %></td>
            </tr>
            <tr class="label-cell">
              <td>Account</td>
              <td><%= @transaction.account.name %></td>
            </tr>
            <tr class="label-cell">
              <td>Category</td>
              <td><%= @transaction.category.humanized_name %></td>
            </tr>
          </tbody>
        </table>
      </div>
      <%= if @transaction.extra do %>
        <div class="data-table card">
          <table>
            <tbody>
              <tr>
                <td colspan="2"><strong>Transaction Info</strong></td>
              </tr>
              <tr>
                <td>Payee</td>
                <td><%= @transaction.extra["payee"] %></td>
              </tr>
              <tr>
                <td>Information</td>
                <td><%= @transaction.extra["information"] %></td>
              </tr>
              <tr>
                <td>Time</td>
                <td><%= @transaction.extra["time"] %></td>
              </tr>
              <tr>
                <td>Posting date</td>
                <td><%= @transaction.extra["posting_date"] %></td>
              </tr>
              <tr>
                <td>Posting time</td>
                <td><%= @transaction.extra["posting_time"] %></td>
              </tr>
            </tbody>
          </table>
        </div>
      <% end %>
    </div>
  </div>
</div>